spring:
  application:
    name: inditex

  datasource:
    url: jdbc:h2:mem:inditexdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always